### ISSUE TITLE
Cannot build on Ubuntu 14.04 LTS: libtasn1.h: No such file or directory

### ISSUE THREAD

**Issue by zhengcai** [videolabs/libdsm#124]
After the following steps:

sudo apt-get install build-essential autoconf libtool pkg-config libtasn1-3-dev libtasn1-3-bin libbsd-dev
./bootstrap
./configure --prefix=/my/prefix
make

I got the following error:

make[1]: Entering directory '/home/zhengcai/workspace/libdsm'
  CC       contrib/spnego/spnego_asn1.lo
contrib/spnego/spnego_asn1.c:5:22: fatal error: libtasn1.h: No such file or directory
 #include <libtasn1.h>
                      ^
compilation terminated.
Makefile:814: recipe for target 'contrib/spnego/spnego_asn1.lo' failed
make[1]: *** [contrib/spnego/spnego_asn1.lo] Error 1
make[1]: Leaving directory '/home/zhengcai/workspace/libdsm'
Makefile:496: recipe for target 'all' failed
make: *** [all] Error 2

Any idea on what is happening? (libtasn1.h is indeed in /usr/include). And how should I fix this problem?

Thanks

**Comment by jbkempf** [comment]
Did it detect tasn1 correctly in configure? Did you check the config.log?
